### ISSUE TITLE
ARM binaries

### ISSUE THREAD

**Issue by lattedesu** [avahowell/sia-coldstorage#1]
Hello,

I was wondering if there are any plans for ARM binaries as release.

[Raspberry Pi](https://www.raspberrypi.org/help/what-%20is-a-raspberry-pi/) is a great tiny machine to make an airgapped Linux environment, and to compile the code, internet is required for dependencies.

I'd appreciate if this could be considered.

Thanks in advance,

**Comment by tbenz9** [comment]
I downloaded the latest from master and built it.
`tbenz9@raspberrypi:~/go/github.com/sia-coldstorage $ md5sum main
ec6912ad182614a000c115dc21dab375  main
tbenz9@raspberrypi:~/go/github.com/sia-coldstorage $ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`

I'd be happy to submit my builds to @avahowell if she want's to add them to the repo.

**Comment by avahowell** [comment]
I've added ARM binaries to the latest release, 0.2.1. Closing this issue
